---
trigger:
  - main

variables:
  vmImage: ubuntu-latest
  azureSubscription: www.teglgarden.dk
  resourceGroupName: ondfisk
  location: northeurope

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImage)
        steps:
          - task: AzureCLI@2
            displayName: Build Bicep Template
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az bicep build --file $(Build.SourcesDirectory)/azuredeploy.bicep
          - task: CopyFiles@2
            displayName: Copy Files
            inputs:
              Contents: |
                $(Build.SourcesDirectory)/**/*.json
              targetFolder: $(Build.ArtifactStagingDirectory)
          - task: PublishPipelineArtifact@1
            displayName: Publish Pipeline Artifact
            inputs:
              artifactName: drop
              targetPath: $(Build.ArtifactStagingDirectory)

  - stage: Validate
    displayName: Validate
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: Validate
        displayName: Validate
        environment: Production
        pool:
          vmImage: $(vmImage)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureResourceManagerTemplateDeployment@3
                  displayName: Validate Azure Resources Deployment
                  inputs:
                    azureResourceManagerConnection: $(azureSubscription)
                    resourceGroupName: $(resourceGroupName)
                    location: $(location)
                    csmFile: $(Pipeline.Workspace)/drop/azuredeploy.json
                    csmParametersFile: $(Pipeline.Workspace)/drop/azuredeploy.parameters.json
                    deploymentMode: Validation

  - stage: Deploy
    displayName: Deploy
    dependsOn: Validate
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - deployment: Deploy
        displayName: Deploy
        environment: Production
        pool:
          vmImage: $(vmImage)
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzureResourceManagerTemplateDeployment@3
                  displayName: Deploy Azure Resources
                  inputs:
                    azureResourceManagerConnection: $(azureSubscription)
                    resourceGroupName: $(resourceGroupName)
                    location: $(location)
                    csmFile: $(Pipeline.Workspace)/drop/azuredeploy.json
                    csmParametersFile: $(Pipeline.Workspace)/drop/azuredeploy.parameters.json
                    deploymentMode: Incremental
                    deploymentOutputs: armOutputs
                - task: PowerShell@2
                  displayName: Parse Deployment Output
                  inputs:
                    targetType: inline
                    script: |
                      $output = '$(armOutputs)' | ConvertFrom-Json

                      $output.PSObject.Properties | ForEach-Object {
                          $type = $PSItem.Value.type
                          $name = $PSItem.Name
                          $value = $PSItem.Value.value

                          if ($type -eq "SecureString") {
                              Write-Host "##vso[task.setvariable variable=$name;issecret=true]$value"
                          }
                          elseif ($type -eq "String") {
                              Write-Host "##vso[task.setvariable variable=$name]$value"
                          }
                          else {
                              $value = $value | ConvertTo-Json -Compress
                              Write-Host "##vso[task.setvariable variable=$name]$value"
                          }
                      }
                - task: AzureStaticWebApp@0
                  displayName: Deploy Web App
                  inputs:
                    app_location: ./wwwroot
                    azure_static_web_apps_api_token: $(deploymentToken)
